/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Mascota;
import modelo.Propietario;
import modelo.Vacuna;

/**
 *
 * @author MI PC
 */
public class VentanaVacuna extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMascota
     */
//---------------Constructor de la ventana-------------------------------
    public VentanaVacuna() {
        // Inicializa los componentes del formulario
        initComponents();
        setTitle("Registro de Vacunas");
        //ubicacion de la ventana
        setLocationRelativeTo(null);
        // Cierra solo esta ventana
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        limpiarCampos();
        llenarTabla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVacunas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFechaVacuna = new javax.swing.JTextField();
        txtMascota = new javax.swing.JTextField();
        txtLote = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtProximaDosis = new javax.swing.JTextField();
        cbTipoVacuna = new javax.swing.JComboBox<>();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..............................Vacunas.....................................", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Gabriola", 0, 36), new java.awt.Color(0, 0, 0))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(102, 102, 255));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..........................................................Citas Agendadas...........................................................................", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        tblVacunas.setBackground(new java.awt.Color(153, 153, 255));
        tblVacunas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblVacunas.setForeground(new java.awt.Color(0, 0, 0));
        tblVacunas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Fecha ", "Lote", "Mascota", "Tipo de vacuna", "Proxima Dosis"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblVacunas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setForeground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Fecha:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Lote:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mascota:");

        txtFechaVacuna.setBackground(new java.awt.Color(102, 102, 255));
        txtFechaVacuna.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtFechaVacuna.setForeground(new java.awt.Color(0, 0, 0));
        txtFechaVacuna.setToolTipText("Ingresa nombre del propietario");

        txtMascota.setBackground(new java.awt.Color(102, 102, 255));
        txtMascota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtMascota.setForeground(new java.awt.Color(0, 0, 0));

        txtLote.setBackground(new java.awt.Color(102, 102, 255));
        txtLote.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtLote.setForeground(new java.awt.Color(0, 0, 0));

        btnEliminar.setBackground(new java.awt.Color(102, 102, 255));
        btnEliminar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnEliminar.setText("Eliminar");

        btnGuardar.setBackground(new java.awt.Color(102, 102, 255));
        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(102, 102, 255));
        btnEditar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(102, 102, 255));
        btnBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tipo de vacuna:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Proxima dosis:");

        txtProximaDosis.setBackground(new java.awt.Color(102, 102, 255));
        txtProximaDosis.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtProximaDosis.setForeground(new java.awt.Color(0, 0, 0));

        cbTipoVacuna.setBackground(new java.awt.Color(102, 102, 255));
        cbTipoVacuna.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbTipoVacuna.setForeground(new java.awt.Color(0, 0, 0));
        cbTipoVacuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---", "Multiple(perros)", "Contra la Rabia", "Triple felina", "Cuadruple felina(leucemia)", "Otro" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(btnBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEditar)
                        .addGap(36, 36, 36)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar)
                        .addGap(27, 27, 27))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtFechaVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtProximaDosis, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(cbTipoVacuna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFechaVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbTipoVacuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtProximaDosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnGuardar))
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Agendar", jPanel3);

        btnRegresar.setBackground(new java.awt.Color(102, 102, 255));
        btnRegresar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnRegresar.setText("Regresar ");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Ventana1 v1 = new Ventana1();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String fecha = txtFechaVacuna.getText();
        String lote = txtLote.getText().trim();
        String nombreM = txtMascota.getText();
        String tipoVacuna = (String) cbTipoVacuna.getSelectedItem();
        String proximaDosis = txtProximaDosis.getText();

        // Validar campos vacios
        if (fecha.isEmpty() || lote.isEmpty() || nombreM.isEmpty() || tipoVacuna == null || proximaDosis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar la mascota asociada recorriendo todos los propietarios
        Mascota mascota = null;
        for (Propietario propi : Propietario.listaPropietarios) {
            for (Mascota masco : propi.getListaMascotas()) {
                if (masco.getNombreM().equalsIgnoreCase(nombreM)) {
                    mascota = masco;
                    break;
                }
            }
            if (mascota != null) {
                break;
            }
        }

        // Validar si se encontro la mascota
        if (mascota == null) {
            JOptionPane.showMessageDialog(this, "La mascota no esta registrada.... Registrala primero",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el objeto Vacuna
        Vacuna vacuna = new Vacuna(fecha, lote, mascota, tipoVacuna, proximaDosis);

        // Guardar la vacuna en la lista
        Vacuna.listaVacunas.add(vacuna);

        // Mensaje de confirmación
        JOptionPane.showMessageDialog(this,
                "---------Vacuna registrada:-----------\n"
                + "Fecha: " + fecha + "\n"
                + "Lote: " + lote + "\n"
                + "Mascota: " + mascota.getNombreM() + "\n"
                + "Tipo: " + tipoVacuna + "\n"
                + "Proxima dosis: " + proximaDosis);

        // Limpiar campos y actualizar tabla
        limpiarCampos();
        llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String fecha = txtFechaVacuna.getText().trim();

        // Validar si el campo de fecha esta vacio
        if (fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese la fecha de la vacuna a buscar");
            return;
        }

        // Buscar vacuna en la lista
        Vacuna vacunaEncontrada = null;
        for (Vacuna v : Vacuna.listaVacunas) {
            if (v.getFechaVacuna().equalsIgnoreCase(fecha)) {
                vacunaEncontrada = v;
                break;
            }
        }

        // Verificar si se encontro
        if (vacunaEncontrada != null) {
            // Mostrar los datos en el formulario
            txtLote.setText(vacunaEncontrada.getLote());
            txtMascota.setText(vacunaEncontrada.getMascota().getNombreM());
            cbTipoVacuna.setSelectedItem(vacunaEncontrada.getTipoDeVacuna());
            txtProximaDosis.setText(vacunaEncontrada.getProximaDosis());

            JOptionPane.showMessageDialog(this, "Vacuna encontrada");
        } else {
            JOptionPane.showMessageDialog(this, "No se encontro ninguna vacuna con esa fecha");
        }                
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        String fecha = txtFechaVacuna.getText();
        String lote = txtLote.getText().trim();
        String nombreM = txtMascota.getText();
        String tipoVacuna = (String) cbTipoVacuna.getSelectedItem();
        String proximaDosis = txtProximaDosis.getText();

        // Validar campos vacios
        if (fecha.isEmpty() || lote.isEmpty() || nombreM.isEmpty() || tipoVacuna == null || proximaDosis.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buscar la mascota asociada recorriendo todos los propietarios
        Mascota mascota = null;
        for (Propietario propi : Propietario.listaPropietarios) {
            for (Mascota masco : propi.getListaMascotas()) {
                if (masco.getNombreM().equalsIgnoreCase(nombreM)) {
                    mascota = masco;
                    break;
                }
            }
            if (mascota != null) {
                break;
            }
        }

        // Validar si se encontro la mascota
        if (mascota == null) {
            JOptionPane.showMessageDialog(this, "La mascota no esta registrada.... Registrala primero",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Buscar vacuna en la lista
        Vacuna vacunaEncontrada = null;
        for (Vacuna v : Vacuna.listaVacunas) {
            if (v.getFechaVacuna().equalsIgnoreCase(fecha)) {
                vacunaEncontrada = v;
                break;
            }

            // Actualizar los datos de la vacuna
            vacunaEncontrada.setLote(lote);
            vacunaEncontrada.setMascota(mascota);
            vacunaEncontrada.setTipoDeVacuna(tipoVacuna);
            vacunaEncontrada.setProximaDosis(proximaDosis);

            JOptionPane.showMessageDialog(this, "Vacuna editada correctamente");
        
        // Limpiar campos y actualizar tabla
        limpiarCampos();
        llenarTabla();  
        }
    }//GEN-LAST:event_btnEditarActionPerformed

//-----------creo metodo limpiar Campos----------------------
    private void limpiarCampos() {
        txtFechaVacuna.setText("");
        txtLote.setText("");
        txtMascota.setText("");
        cbTipoVacuna.setSelectedIndex(0); //selecciona la primera opcion
        txtProximaDosis.setText("");
    }
//------------creo metodo de llenar tabla------------------------

    private void llenarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tblVacunas.getModel();
        modelo.setRowCount(0); // Limpia la tabla antes de llenarla

        for (Vacuna vacuna : Vacuna.listaVacunas) {
            modelo.addRow(new Object[]{
                vacuna.getFechaVacuna(),
                vacuna.getLote(),
                vacuna.getMascota().getNombreM(),
                vacuna.getTipoDeVacuna(),
                vacuna.getProximaDosis()
            });
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVacuna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVacuna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbTipoVacuna;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblVacunas;
    private javax.swing.JTextField txtFechaVacuna;
    private javax.swing.JTextField txtLote;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtProximaDosis;
    // End of variables declaration//GEN-END:variables
}
