/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Consulta;
import modelo.Mascota;
import modelo.Propietario;
import modelo.Veterinario;

/**
 *
 * @author MI PC
 */
public class VentanaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsulta
     */
    public VentanaConsulta() {
        initComponents();
        setTitle("Registro de consulta");
        //cerrar ventana
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        limpiarCampos();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        cbVeterinarios = new javax.swing.JComboBox<>();
        txtMascota = new javax.swing.JTextField();
        txtDiagnostico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTratamiento = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMedicamentos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultas = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, ".....................Registro de Consultas......................", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Gabriola", 0, 36), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jTabbedPane1.setBackground(new java.awt.Color(51, 255, 51));
        jTabbedPane1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(102, 255, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Codigo:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Veterinario:");

        txtCodigo.setBackground(new java.awt.Color(0, 204, 102));
        txtCodigo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(0, 0, 0));

        txtFecha.setBackground(new java.awt.Color(0, 204, 102));
        txtFecha.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtFecha.setForeground(new java.awt.Color(0, 0, 0));
        txtFecha.setToolTipText("dd/mm/aaaa");

        btnGuardar.setBackground(new java.awt.Color(0, 153, 0));
        btnGuardar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(0, 153, 0));
        btnEliminar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(0, 153, 0));
        btnEditar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 153, 0));
        btnBuscar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        cbVeterinarios.setBackground(new java.awt.Color(0, 204, 102));
        cbVeterinarios.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cbVeterinarios.setForeground(new java.awt.Color(0, 0, 0));
        cbVeterinarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---" }));

        txtMascota.setBackground(new java.awt.Color(0, 204, 102));
        txtMascota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtMascota.setForeground(new java.awt.Color(0, 0, 0));
        txtMascota.setToolTipText("nombre de la mascota");

        txtDiagnostico.setBackground(new java.awt.Color(0, 204, 102));
        txtDiagnostico.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtDiagnostico.setForeground(new java.awt.Color(0, 0, 0));
        txtDiagnostico.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Mascota:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Diagnostico:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tratamiento:");

        txtTratamiento.setBackground(new java.awt.Color(0, 204, 102));
        txtTratamiento.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtTratamiento.setForeground(new java.awt.Color(0, 0, 0));
        txtTratamiento.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Medicamentos:");

        txtMedicamentos.setBackground(new java.awt.Color(0, 204, 102));
        txtMedicamentos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        txtMedicamentos.setForeground(new java.awt.Color(0, 0, 0));
        txtMedicamentos.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar)
                .addGap(18, 18, 18)
                .addComponent(btnGuardar)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnBuscar)
                        .addGap(36, 36, 36)
                        .addComponent(btnEditar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtFecha, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMascota, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiagnostico, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTratamiento, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVeterinarios, javax.swing.GroupLayout.Alignment.LEADING, 0, 237, Short.MAX_VALUE)
                            .addComponent(txtMedicamentos, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigo))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiagnostico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTratamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbVeterinarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnEditar)
                    .addComponent(btnBuscar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro", jPanel2);

        jPanel3.setBackground(new java.awt.Color(102, 255, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "..............................................................Consultas.......................................................................", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        tblConsultas.setBackground(new java.awt.Color(0, 204, 51));
        tblConsultas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tblConsultas.setForeground(new java.awt.Color(0, 0, 0));
        tblConsultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Fecha", "Mascota", "Diagnostico", "Tratamiento", "Medicamento", "Veterinario"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblConsultas);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tabla", jPanel3);

        btnRegresar.setBackground(new java.awt.Color(51, 204, 0));
        btnRegresar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegresar))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Ventana1 v1 = new Ventana1();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
    //--------Obtener el codigo ingresado-------------
    String codigo = txtCodigo.getText();

    // Validar si el campo esta vacio
    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Dame el codigo de la consulta a buscar");
        return;
    }

    //-----------Buscar la consulta por codigo----------------
    Consulta consulta = Consulta.buscarConsulta(codigo);

    if (consulta != null) {
        //----------Mostrar los datos en los campos--------------
        txtFecha.setText(consulta.getFecha());
        txtMascota.setText(consulta.getMascota().getNombreM());
        txtDiagnostico.setText(consulta.getDiagnostico());
        txtTratamiento.setText(consulta.getTratamiento());
        txtMedicamentos.setText(consulta.getMedicamentos());
        
        JOptionPane.showMessageDialog(this,"Se encontro consulta");
    } else {
        JOptionPane.showMessageDialog(this, "No se encontro una consulta con ese codigo");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
    String codigo = txtCodigo.getText();                        
    String fecha = txtFecha.getText();                          
    String nombreM = txtMascota.getText();          
    String diagnostico = txtDiagnostico.getText();              
    String tratamiento = txtTratamiento.getText();              
    String medicamentos = txtMedicamentos.getText();            
    

    // ------------------Validar campos vacios ---------------------
    if (codigo.isEmpty() || fecha.isEmpty() || nombreM.isEmpty() ||
        diagnostico.isEmpty() || tratamiento.isEmpty() || medicamentos.isEmpty()) {

        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Buscar mascota registrada
     Mascota mascota = null;
    for (Propietario p : Propietario.listaPropietarios) {
        for (Mascota m : p.getListaMascotas()) {
            if (m.getNombreM().equalsIgnoreCase(nombreM)) {
                mascota = m;
                break;
            }
        }
        if (mascota != null) break;
    }

    if (mascota == null) {
        JOptionPane.showMessageDialog(this, "La mascota no esta registrada...Registrela primero");
        return;
    }


    // Crear objeto consulta
    Consulta consulta = new Consulta(codigo, fecha, mascota, diagnostico, tratamiento, medicamentos);
// Guardar en la lista general
    Consulta.guardarConsulta(consulta);

    // Asociar consulta a la mascota
    mascota.guardarConsulta(consulta);
    
    // ------------------Mostrar mensaje de confirmacion ---------------------
    JOptionPane.showMessageDialog(this, 
            "--------------Consulta registrada:---------------\n" +
            "Codigo: " + codigo + "\n" +
            "Fecha: " + fecha + "\n" +
            "Mascota: " + mascota.getNombreM() + "\n" +
            "Diagnostico: " + diagnostico + "\n" +
            "Tratamiento: " + tratamiento + "\n" +
            "Medicamentos: " + medicamentos);

    // ------------------Limpiar campos y actualizar tabla ---------------------
    limpiarCampos();
    llenarTabla();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
    String codigo = txtCodigo.getText();                        
    String fecha = txtFecha.getText();                          
    String nombreM = txtMascota.getText();          
    String diagnostico = txtDiagnostico.getText();              
    String tratamiento = txtTratamiento.getText();              
    String medicamentos = txtMedicamentos.getText();            

    // ------------------Validar campos vacios ---------------------
    if (codigo.isEmpty() || fecha.isEmpty() || nombreM.isEmpty() ||
        diagnostico.isEmpty() || tratamiento.isEmpty() || medicamentos.isEmpty()) {

        JOptionPane.showMessageDialog(this,"Por favor complete todos los campos",
                "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
 
    //-------Creo una variable que al principio estara vacia para buscar si la mascota 
    //esta registrada-----------------
    Mascota mascota = null;
    for (Propietario p : Propietario.listaPropietarios) {
        for (Mascota m : p.getListaMascotas()) {
            if (m.getNombreM().equalsIgnoreCase(nombreM)) {
                mascota = m;
                break;
            }
        }
        if (mascota != null) break;
    }

    if (mascota == null) {
        JOptionPane.showMessageDialog(this, "La mascota no esta registrada","Error",
                JOptionPane.ERROR_MESSAGE);
        return;
    }

    //----------Llamar al metodo para editar la consulta------------------
    boolean editado = Consulta.editarConsulta(codigo, fecha, mascota, diagnostico, tratamiento, medicamentos);
    if (editado) {
        JOptionPane.showMessageDialog(this, "Editaste la consulta");
        limpiarCampos();
        llenarTabla();
    } else {
        JOptionPane.showMessageDialog(this, "Consulta no encontrada o datos invalidos","Error",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo = txtCodigo.getText();
        
    //------------miro si el campo esta vacio---------------
    if (codigo.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Dame el codigo de la consulta a eliminar");
        return;
    }

    //---------------Confirmar eliminacion----------------------
    int confirmacion = JOptionPane.showConfirmDialog(this,
        "¿Esta seguro de eliminar la consulta con codigo " + codigo + "?",
        "Confirmar", JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        boolean eliminado = Consulta.eliminarConsulta(codigo);

        if (eliminado) {
            JOptionPane.showMessageDialog(this, "Consulta eliminada");
            limpiarCampos();
            llenarTabla();
        } else {
            JOptionPane.showMessageDialog(this, "Consulta no encontrada");
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed
    //-----------creo metodo de limpiar campos----------------------

    private void limpiarCampos() {
        txtCodigo.setText("");
        txtFecha.setText("");
        txtMascota.setText("");
        txtDiagnostico.setText("");
        txtTratamiento.setText("");
        txtMedicamentos.setText("");  
    }

//------------creo metodo de llenar tabla------------------------
    private void llenarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tblConsultas.getModel();
    modelo.setRowCount(0); // Limpia la tabla

    for (Consulta consulta : Consulta.listaConsultas) {
        modelo.addRow(new Object[]{
            consulta.getCodigo(),                         
            consulta.getFecha(), 
            consulta.getMascota().getNombreM(),
            consulta.getDiagnostico(),
            consulta.getTratamiento(),
            consulta.getMedicamentos(),
        });
    }
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbVeterinarios;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblConsultas;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDiagnostico;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtMedicamentos;
    private javax.swing.JTextField txtTratamiento;
    // End of variables declaration//GEN-END:variables
}
